'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cat_Oficina_MergeLog
    Public Property IdLog As Integer
    Public Property Fecha As Nullable(Of Date)
    Public Property IdFrom As Nullable(Of Integer)
    Public Property IdTo As Nullable(Of Integer)
    Public Property NombreFrom As String
    Public Property NombreTo As String
    Public Property Reason As String

End Class
