'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cat_Oficina_Backup_20260203_093509
    Public Property IdOficina As Integer
    Public Property Nombre As String
    Public Property EsExterna As Nullable(Of Boolean)
    Public Property Direccion As String

End Class
