'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cat_Usuario
    Public Property IdUsuario As Integer
    Public Property NombreCompleto As String
    Public Property UsuarioLogin As String
    Public Property Activo As Nullable(Of Boolean)
    Public Property Clave As String
    Public Property Rol As String
    Public Property IdOficina As Nullable(Of Integer)

    Public Overridable Property Cat_Oficina As Cat_Oficina
    Public Overridable Property Mae_Documento As ICollection(Of Mae_Documento) = New HashSet(Of Mae_Documento)
    Public Overridable Property Tra_Movimiento As ICollection(Of Tra_Movimiento) = New HashSet(Of Tra_Movimiento)
    Public Overridable Property EventosSistema As ICollection(Of EventosSistema) = New HashSet(Of EventosSistema)
    Public Overridable Property Mae_CuposSecretaria As ICollection(Of Mae_CuposSecretaria) = New HashSet(Of Mae_CuposSecretaria)

End Class
