'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cat_TipoDocumento
    Public Property IdTipo As Integer
    Public Property Nombre As String
    Public Property Codigo As String
    Public Property EsInterno As Nullable(Of Boolean)

    Public Overridable Property Cfg_TiemposRespuesta As ICollection(Of Cfg_TiemposRespuesta) = New HashSet(Of Cfg_TiemposRespuesta)
    Public Overridable Property Mae_Documento As ICollection(Of Mae_Documento) = New HashSet(Of Mae_Documento)
    Public Overridable Property Mae_CuposSecretaria As ICollection(Of Mae_CuposSecretaria) = New HashSet(Of Mae_CuposSecretaria)
    Public Overridable Property Mae_NumeracionRangos As ICollection(Of Mae_NumeracionRangos) = New HashSet(Of Mae_NumeracionRangos)

End Class
