'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cfg_TiemposRespuesta
    Public Property IdConfig As Integer
    Public Property IdTipoDocumento As Integer
    Public Property Prioridad As String
    Public Property DiasMaximos As Integer
    Public Property HorasMaximas As Nullable(Of Integer)

    Public Overridable Property Cat_TipoDocumento As Cat_TipoDocumento

End Class
