'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cfg_SistemaParametros
    Public Property IdParametro As Integer
    Public Property Clave As String
    Public Property Valor As String
    Public Property Descripcion As String
    Public Property UsuarioActualizacion As String
    Public Property FechaActualizacion As Date

End Class
