'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cfg_TiemposRespuesta_Historial
    Public Property IdHist As Integer
    Public Property IdConfigOriginal As Integer
    Public Property IdTipoDocumento As Integer
    Public Property Prioridad As String
    Public Property DiasAnteriores As Nullable(Of Integer)
    Public Property DiasNuevos As Nullable(Of Integer)
    Public Property FechaCambio As Nullable(Of Date)
    Public Property UsuarioSistema As String

End Class
