'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EventosSistema
    Public Property IdEvento As Long
    Public Property UsuarioId As Integer
    Public Property FechaEvento As Nullable(Of Date)
    Public Property Descripcion As String
    Public Property Modulo As String

    Public Overridable Property Usuarios As Usuarios
    Public Overridable Property Cat_Usuario As Cat_Usuario

End Class
