'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Mae_Reclusos
    Public Property IdRecluso As Integer
    Public Property NombreCompleto As String
    Public Property Activo As Nullable(Of Boolean)
    Public Property Documento As String

    Public Overridable Property Tra_SalidasLaborales As ICollection(Of Tra_SalidasLaborales) = New HashSet(Of Tra_SalidasLaborales)

End Class
