'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Mae_Documento
    Public Property IdDocumento As Long
    Public Property IdTipo As Integer
    Public Property NumeroOficial As String
    Public Property NumeroInterno As String
    Public Property Asunto As String
    Public Property Descripcion As String
    Public Property FechaCreacion As Nullable(Of Date)
    Public Property FechaRecepcion As Nullable(Of Date)
    Public Property Fojas As Nullable(Of Integer)
    Public Property IdDocumentoPadre As Nullable(Of Long)
    Public Property IdHiloConversacion As System.Guid
    Public Property IdEstadoActual As Integer
    Public Property IdOficinaActual As Integer
    Public Property IdUsuarioCreador As Nullable(Of Integer)
    Public Property FechaVencimiento As Nullable(Of Date)
    Public Property EstadoSemaforo As String

    Public Overridable Property Cat_Estado As Cat_Estado
    Public Overridable Property Cat_Oficina As Cat_Oficina
    Public Overridable Property Cat_TipoDocumento As Cat_TipoDocumento
    Public Overridable Property Cat_Usuario As Cat_Usuario
    Public Overridable Property Mae_Documento1 As ICollection(Of Mae_Documento) = New HashSet(Of Mae_Documento)
    Public Overridable Property Mae_Documento2 As Mae_Documento
    Public Overridable Property Tra_Movimiento As ICollection(Of Tra_Movimiento) = New HashSet(Of Tra_Movimiento)
    Public Overridable Property Tra_AdjuntoDocumento As ICollection(Of Tra_AdjuntoDocumento) = New HashSet(Of Tra_AdjuntoDocumento)

End Class
