'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Mae_NumeracionRangos
    Public Property IdRango As Integer
    Public Property IdTipo As Integer
    Public Property NombreRango As String
    Public Property NumeroInicio As Integer
    Public Property NumeroFin As Integer
    Public Property UltimoUtilizado As Integer
    Public Property Activo As Boolean
    Public Property FechaCreacion As Nullable(Of Date)

    Public Overridable Property Cat_TipoDocumento As Cat_TipoDocumento

End Class
