'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Mae_CuposSecretaria
    Public Property IdCupo As Integer
    Public Property Fecha As Date
    Public Property IdUsuario As Nullable(Of Integer)
    Public Property IdTipo As Integer
    Public Property Cantidad As Integer

    Public Overridable Property Cat_TipoDocumento As Cat_TipoDocumento
    Public Overridable Property Cat_Usuario As Cat_Usuario

End Class
