'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class SecretariaDBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SecretariaDBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Cat_Estado() As DbSet(Of Cat_Estado)
    Public Overridable Property Cat_Oficina() As DbSet(Of Cat_Oficina)
    Public Overridable Property Cat_TipoDocumento() As DbSet(Of Cat_TipoDocumento)
    Public Overridable Property Cat_Usuario() As DbSet(Of Cat_Usuario)
    Public Overridable Property Mae_Documento() As DbSet(Of Mae_Documento)
    Public Overridable Property Mae_NumeracionRangos() As DbSet(Of Mae_NumeracionRangos)
    Public Overridable Property Mae_Reclusos() As DbSet(Of Mae_Reclusos)
    Public Overridable Property Tra_Movimiento() As DbSet(Of Tra_Movimiento)

End Class
