'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class SecretariaDBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SecretariaDBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Cat_Estado() As DbSet(Of Cat_Estado)
    Public Overridable Property Cat_Oficina() As DbSet(Of Cat_Oficina)
    Public Overridable Property Cat_Oficina_MergeLog() As DbSet(Of Cat_Oficina_MergeLog)
    Public Overridable Property Cat_TipoDocumento() As DbSet(Of Cat_TipoDocumento)
    Public Overridable Property Cat_Usuario() As DbSet(Of Cat_Usuario)
    Public Overridable Property EventosSistema() As DbSet(Of EventosSistema)
    Public Overridable Property Mae_Documento() As DbSet(Of Mae_Documento)
    Public Overridable Property Mae_NumeracionRangos() As DbSet(Of Mae_NumeracionRangos)
    Public Overridable Property Mae_Reclusos() As DbSet(Of Mae_Reclusos)
    Public Overridable Property Tra_Movimiento() As DbSet(Of Tra_Movimiento)
    Public Overridable Property Usuarios() As DbSet(Of Usuarios)
    Public Overridable Property Cat_Oficina_Backup_20260203_093509() As DbSet(Of Cat_Oficina_Backup_20260203_093509)
    Public Overridable Property Tra_AdjuntoDocumento() As DbSet(Of Tra_AdjuntoDocumento)

    Public Overridable Function sp_UnificarOficinas(nombreDestino As String, listaIdsBorrar As String) As ObjectResult(Of sp_UnificarOficinas_Result)
        Dim nombreDestinoParameter As ObjectParameter = If(nombreDestino IsNot Nothing, New ObjectParameter("NombreDestino", nombreDestino), New ObjectParameter("NombreDestino", GetType(String)))

        Dim listaIdsBorrarParameter As ObjectParameter = If(listaIdsBorrar IsNot Nothing, New ObjectParameter("ListaIdsBorrar", listaIdsBorrar), New ObjectParameter("ListaIdsBorrar", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_UnificarOficinas_Result)("sp_UnificarOficinas", nombreDestinoParameter, listaIdsBorrarParameter)
    End Function

End Class
