'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tra_AdjuntoDocumento
    Public Property IdAdjunto As Long
    Public Property IdDocumento As Long
    Public Property StoredName As String
    Public Property DisplayName As String
    Public Property AddedAt As Date
    Public Property Content As Byte()

    Public Overridable Property Mae_Documento As Mae_Documento

End Class
