'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tra_SalidasLaboralesDocumentoRespaldo
    Public Property IdSalidaDocumentoRespaldo As Integer
    Public Property IdSalida As Integer
    Public Property IdDocumento As Long
    Public Property FechaRegistro As Date

    Public Overridable Property Mae_Documento As Mae_Documento
    Public Overridable Property Tra_SalidasLaborales As Tra_SalidasLaborales

End Class
