'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tra_Movimiento
    Public Property IdMovimiento As Long
    Public Property IdDocumento As Long
    Public Property FechaMovimiento As Nullable(Of Date)
    Public Property IdOficinaOrigen As Integer
    Public Property IdOficinaDestino As Integer
    Public Property IdUsuarioResponsable As Nullable(Of Integer)
    Public Property ObservacionPase As String
    Public Property IdEstadoEnEseMomento As Nullable(Of Integer)

    Public Overridable Property Cat_Estado As Cat_Estado
    Public Overridable Property Cat_Oficina As Cat_Oficina
    Public Overridable Property Cat_Oficina1 As Cat_Oficina
    Public Overridable Property Cat_Usuario As Cat_Usuario
    Public Overridable Property Mae_Documento As Mae_Documento

End Class
