'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuarios
    Public Property Id As Integer
    Public Property NombreUsuario As String
    Public Property Clave As String
    Public Property Rol As String
    Public Property Activo As Nullable(Of Boolean)

    Public Overridable Property EventosSistema As ICollection(Of EventosSistema) = New HashSet(Of EventosSistema)

End Class
